<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

// Remove some options from the select in order to keep only value suggests vocabs,
// since it can't be done via the core helper.
$dataTypeSelect = $this->dataType()->getSelect('data_type', null, ['class' => 'chosen-select-list']);
$dataTypeSelect = preg_replace([
    '~^(?!(<select name="data_type" class="chosen-select-list">|<optgroup label=".*<option value="valuesuggest.*?</option>|<option value="valuesuggest.*?</option>)).*~m',
    '~(<optgroup.*?>|</optgroup>|<option value="valuesuggest&#x3A;any">.*?</option>)~',
    '~<option value="">.*?</option>~',
], ['', '', '<option value="">' . $translate('Select a vocabulary…') . '</option>'], $dataTypeSelect) . '</select>';
echo $dataTypeSelect;
?>

<div class="js-any-block">
    <div class="valuesuggest-language-container">
        <a class="value-language label o-icon-language" title="<?php echo $escape($translate('Set language')); ?>" aria-label="<?php echo $escape($translate('Set language')); ?>"></a>
        <?php echo $this->formText($languageInput); ?>
        <a href="#" class="value-language remove o-icon-close" title="<?php echo $escape($translate('Remove language')); ?>"></a>
    </div>
    <div class="valuesuggest-vocab-container">
        <span class="o-icon-vocab label" title="<?php echo $escape($rdfLabel); ?>"><?php echo $this->escapeHtml($rdfLabel); ?></span>
        <input type="text" class="valuesuggest-input">
        <?php echo $this->formHidden($labelInput); ?>
        <?php echo $this->formHidden($idInput); ?>
        <div class="valuesuggest-input-value"><?php echo $this->formHidden($valueInput); ?></div>
    </div>
    <div class="valuesuggest-id-container">
        <span class="o-icon-uri label" title="<?php echo $escape($translate('URI')); ?>" aria-label="<?php echo $escape($translate('URI')); ?>"></span>
        <span class="valuesuggest-id"></span>
        <a href="#" class="valuesuggest-id-remove o-icon-close" title="<?php echo $escape($translate('Remove URI')); ?>"></a>
    </div>
</div>
