<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<div class="language-wrapper">
    <?php echo $this->hyperlink('', '#', ['class' => 'value-language o-icon-language', 'title' => $translate('Set language'), ]); ?>
    <label class="language-label">
        <span class="value-label-text"><?php echo $translate('Language'); ?></span>
        <input class="value-language" type="text" list="value-languages" data-value-key="@language">
    </label>
</div>
<div class="valuesuggest-vocab-container">
    <label aria-label="<?php echo $this->escapeHtml($rdfLabel); ?>">
        <span class="o-icon-vocab icon" aria-hidden="true" title="<?php echo $escape($rdfLabel); ?>"></span>
        <input type="text" class="valuesuggest-input">
    </label>
    <?php echo $this->formHidden($labelInput); ?>
    <?php echo $this->formHidden($idInput); ?>
    <?php echo $this->formHidden($valueInput); ?>
</div>
<div class="valuesuggest-id-container">
    <span class="o-icon-uri icon" title="<?php echo $escape($translate('URI')); ?>" aria-label="<?php echo $escape($translate('URI')); ?>"></span>
    <span class="valuesuggest-id"></span>
    <button type="button" class="valuesuggest-id-remove o-icon-close" aria-label="<?php echo $escape($translate('Remove URI')); ?>" title="<?php echo $escape($translate('Remove URI')); ?>"></button>
</div>
